; ===========================================================
; База кухонь Rollclub
; Джерело: Google Sheet
; LastSync: 2026-08-10 10:32:18
; Status: ok | slow | nonstandard | stopped
; Редагування — кнопка Кухні у пульті або Google Sheet
; ===========================================================

[РЕСТОРАН]
City=Харків
Address=пл. Конституції 18(напроти Никольского)
KmlKey=Конституції
Remark=ресторан (напроти Никольского)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[НД]
City=Харків
Address=Садовий проїзд 9(біля магазину Посад)
KmlKey=Нові
Remark=(точка видачі) (біля маг Десятка)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Приморська]
City=Одеса
Address=вул.Незалежності 8гКотовського (красная зона)
Remark=(точка видачі) (вхід через охорону) Орієнтир самовивіз стоматологія "OBLIK" | Скрины в чат
Center=1.5–2
Pickup=60
FarZone=1.5–2
StopList=FALSE

[Мудрого]
City=Дніпро
Address=Князя Ярослава Мудрого, 29 (правый берег)
KmlKey=Мудрого
Remark=(точка видачі) Орієнтир сині ворота зі шлагбаумом з великим надписом ОРЕНДА зліва
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Антонова]
City=Київ
Address=Авіаконструктора Антонова 43 (правий берег )
KmlKey=Антонова
Remark=(точка выдачи)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Драгоманова]
City=Київ
Address=Драгоманова 38 (Лівий берег)
KmlKey=Драгоманова
Remark=(фуд-корт)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Лук'янівка]
City=Київ
Address=Січових Стрільців 26 (Правый берег)
KmlKey=Стрільців
Remark=(фуд-корт)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Троєщина]
City=Київ
Address=Миколи Лаврухіна 12 (Левый берег)
KmlKey=Лаврухіна
Remark=(фуд-корт)Фасад будинку Лаврухіна 12, орієнтир "Біомаркет" наші сусідні двері, з вулиці, не зі сторони підʼїзду
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Крива Липа]
City=Львів
Address=проїзд Крива Липа 8
KmlKey=Липа
Remark=(фуд-корт)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[БЦ]
City=Біла Церква
Address=Вернадського 2в
KmlKey=Церква
Remark=(точка выдачи)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Фудотека]
City=Івано-Франківськ
Address=на Промприладі: вул.Української перемоги, 23
KmlKey=Фудотека
Remark=(фуд корт) вхід знаходиться з вулиці, не з двору
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[ТРЦ Екватор]
City=Рівне
Address=Кулика і Гудачека 23
KmlKey=Екватор
Remark=(фуд корт)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE

[Мегамолл]
City=Вінниця
Address=ТРЦ Мегамолл | вул 600-річчя, 17е
KmlKey=Мегамолл
Remark=3 поверх (біля кафе Гості)
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=FALSE
