; ===========================================================
; База кухонь Rollclub
; Status: ok | slow | nonstandard | stopped
; Редагування — кнопка 🏪 у пульті або вручну тут
; ===========================================================

[РЕСТОРАН]
City=Харків
Address=пл. Конституції 18(напроти Никольского)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[НД]
City=Харків
Address=Садовий проїзд 9(біля маг Десятка)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Приморська]
City=Одеса
Address=вул.Незалежності 8г
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Котовського]
City=Одеса
Address=Котовського (красна зона)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Мудрого]
City=Дніпро
Address=Князя Ярослава Мудрого, 29 (правий берег)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Антонова]
City=Київ
Address=Авіаконструктора Антонова 43 (правий берег)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Драгоманова]
City=Київ
Address=Драгоманова 38 (Лівий берег)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Лук'янівка]
City=Київ
Address=Січових Стрільців 26 (Правий берег)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Троєщина]
City=Київ
Address=Миколи Лаврухіна 12 (Лівий берег)
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Крива Липа]
City=Львів
Address=проїзд Крива Липа 8
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[БЦ]
City=Біла Церква
Address=Вернадського 2в
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Фудотека]
City=Івано-Франківськ
Address=на Промприладі: вул.Української перемоги, 23
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[ТРЦ Екватор]
City=Рівне
Address=Кулика і Гудачека 23
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

[Мегамолл]
City=Вінниця
Address=ТРЦ Мегамолл | вул 600-річчя, 17е
Remark=
Center=Стандарт
Pickup=Стандарт
FarZone=Стандарт
StopList=

